server:
  port: 7777
spring:
  activemq:
    broker-url: tcp://192.168.1.102:61616   #自己的MQ服务地址
    user: admin   #用户名
    password: admin   #密码
  jms:
    pub-sub-domain: true   #false:代表队列  true：代表主题订阅


#自己定义队列名称
myqueue: boot-activemq-queue
mytopic: boot-activemq-topic
